### ISSUE TITLE
WebServices Trouble: Some titles aren't giving results.

### ISSUE THREAD

**Issue by Banane9** [maniaplanet/maniaplanet-ws-sdk#2]
Not an issue with the php sdk, but with the API itself:

When calling `titles/rankings/multiplayer/zone/index.txt?title=TMCanyon&offset=1&length=10` You get this list:  
![Zone Rankings top 10](http://puu.sh/b0gVC/2c34aa5161.png)

But when calling `titles/rankings/multiplayer/player/caymanseb/index.txt?title=TMCanyon`, to get the top player's detailed scores, You get an empty result (null for json):  
![Empty result for top Player in TMCanyon](http://puu.sh/b0h4h/9a9a9ccd89.png)

However, when calling `titles/rankings/multiplayer/player/caymanseb/index.txt?title=TMStadium` for the same Player, You get the normal results, with the ranks for each part of the Zone path:
![Normal Player results in TMStadium](http://puu.sh/b0hbN/7cca6d03df.png)

There's also cases where this is the other way round (i.e. there's results for Canyon, but not for Stadium).

Also, imo, the Offset should start at `0`, because it means _how many You want to skip_, but that's not important now.

**Comment by Banane9** [comment]
Also... could the world rank api return the full path of the Players? So You don't have to query for That again, if You Need it.

Edit: Ok, apparently it gives back the next Zone under the Zone searched for... So for example for the No.2 Driver, it'd be `World|Asia` even when you're looking at world ranks.  
Which makes the paths even more confusing, because he's actually No.1 in `World|Asia`, but that's listed as No.2 ...

**Comment by Banane9** [comment]
And I can do `canyon/rankings/multiplayer/player/banane9/index.txt?title=TMStadium` to get the TMStadium Rankings:  
![TMStadium Rankings with Canyon endpoint](http://puu.sh/b0oc2/65d5f88be0.png)

Which works just like `stadium/rankings/multiplayer/player/banane9/index.txt?title=TMStadium`:  
![TMStadium Rankings with Stadium endpoint](http://puu.sh/b0ofq/53f039df10.png)

But I can't get `canyon/rankings/multiplayer/player/banane9/index.txt?title=TMCanyon` (`title=Canyon` doesn't work either):  
![No TMCanyon Rankings with Canyon endpoint](http://puu.sh/b0ojg/1ec5c21447.png)

Even though `canyon/rankings/multiplayer/player/banane9/index.txt` works:
![Canyon Rankings with Canyon endpoint](http://puu.sh/b0olM/41942539f7.png)

**Comment by Banane9** [comment]
And `titles/rankings/multiplayer/player/proni/index.txt` lists all the Rankings for proni:  
![All Rankings for Proni](http://puu.sh/b0ov2/897364257f.png)

But for me (`titles/rankings/multiplayer/player/banane9/index.txt`) It's an empty `ranks` field:  
![Empty ranks field for me](http://puu.sh/b0oBj/ea850c3413.png)

All the Information is also pretty useless without any info on which title It's for...

**Comment by Banane9** [comment]
@magnetik hello?

**Comment by Banane9** [comment]
And why is it using 0/1 to represent false/true? From `servers/banane9dedicated1/index.json`:

``` JSON
"isOnline":"0",
"isDedicated":"1" 
```

There's perfectly fine true/false values in JSON; no Need to use  0/1. That makes using an automated Parser a pain.

**Comment by Banane9** [comment]
And the filters on the Server list don't do anything... I'm filtering for France and a max ladder range of 5000.0 and the first Server is from Dortmund. `servers/index.txt?zone=World|Europe|France&offset=0&ladderLimitMax=5000.0`:  
![Server List not filtering](http://puu.sh/b2c3q/88aad9a6e6.png)

I'll just make an IEnumerable That automatically queries on ... For Science!

**Comment by Banane9** [comment]
Hello, anyone here?

**Comment by magnetik** [comment]
Hi,

Sorry for the late response (I was on holidays).

This isn't technically an error of the SDK but of the API, you'd better post on the forum and I'll answer once I catched up with everything.

Thanks for the report anyway.

**Comment by Banane9** [comment]
Did That already, [here](http://forum.maniaplanet.com/viewtopic.php?f=282&t=29058)

**Comment by magnetik** [comment]
Okay I'll take a look tomorrow. 

I close it here and we continue there :)
